---
fail_on_violations: true

eslint:
  enabled: true

jshint:
  enabled: true

remark:
  enabled: true

shellcheck:
  enabled: true
  # config_file: .shellcheck.yml  # https://intercom.help/hound/en/articles/2138564-shellcheck

stylelint:
  enabled: true
