---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: "An independent mind..."
title_separator: "-"
subtitle:  # site tagline that appears below site title in masthead
name: "Francis T. O'Donovan"
description: >- # this means to ignore newlines until "baseurl:"
  My home on the web.
baseurl:  # the subpath of your site, e.g. "/blog"
url: "https://proinsias.github.io"
gh_repo: proinsias.github.io
github: [metadata]  # https://github.com/github/pages-gem/issues/399
repository: proinsias/proinsias.github.io
email: francis.odonovan@gmail.com
twitter_username: francisodonovan
github_username: proinsias
minimal_mistakes_skin: "default"  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
teaser:  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
logo:  # "/assets/images/88x88.png"
# breadcrumbs: false # true, false (default)
words_per_minute: 200
comments:
  # yamllint disable-line rule:line-length
  provider: "facebook"  # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname:  # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    # yamllint disable-line rule:line-length
    server:  # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:  # FIXME
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts:  # 5 (default)
    colorscheme:  # "light" (default), "dark"
  utterances:
    theme:  # "github-light" (default), "github-dark"
    issue_term:  # "pathname" (default)
staticman:
  allowedFields:  # ['name', 'email', 'url', 'message']
  branch:  # "master"
  commitMessage:  # "New comment by {fields.name}"
  filename:  # comment-{@timestamp}
  format:  # "yml"
  moderation:  # true
  path:  # "/_data/comments/{options.slug}" (default)
  requiredFields:  # ['name', 'email', 'message']
  transforms:
    email:  # "md5"
  generatedFields:
    date:
      type:  # "date"
      options:
        format:  # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint:  # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey:
  secret:
atom_feed:  # To link to an externally hosted feed
  path:  # blank (default) uses feed.xml
search: true  # true, false (default)
search_full_content:  # true, false (default). Setting to true could impact page load performance.
search_provider:  # lunr (default), algolia, google
algolia:
  application_id:  # YOUR_APPLICATION_ID
  index_name:  # YOUR_INDEX_NAME
  search_only_api_key:  # YOUR_SEARCH_ONLY_API_KEY
  powered_by:  # true (default), false
google:
  search_engine_id:  # YOUR_SEARCH_ENGINE_ID
  instant_search:  # false (default), true

# Build settings
excerpt_separator: "\n\n"
incremental: false
highlighter: rouge
lsi: false
markdown: kramdown
paginate: 5  # amount of posts to show
paginate_path: /page:num/
permalink: /:categories/:title/
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
remote_theme: mmistakes/minimal-mistakes
# Outputting
timezone:  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
strict_front_matter: true  # Fail build if there is a YAML syntax error in a page's front matter.

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - .htaccess
  - .well-known
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - /bin
  - Capfile
  - CHANGELOG
  - config
  - /docs  # Ignore Minimal Mistakes /docs.
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - /templates
  - /test  # Ignore Minimal Mistakes /test.
  - tmp
  - vendor
  - "*.sublime-project"
  - "*.sublime-workspace"

keep_files:
  - .git
  - .svn

# Plugins (previously gems:)
plugins:
  - jekyll-algolia
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-algolia
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

author:
  name: "Francis T. O'Donovan"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Data Science Manager at Hospital IQ – Planet discoverer, researcher, developer, geek."
  location: "Boston, MA"
  email: francis.odonovan@gmail.com
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://proinsias.github.io/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:francis.odonovan@gmail.com"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/francis_odonovan/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/proinsias/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url:  # "https://instagram.com/"
    - label: "KeyBase"
      icon: "fab fa-fw fa-key"
      url: "https://keybase.io/proinsias/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/francistodonovan/"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1257318/proinsias/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/francisodonovan/"

# Site Footer
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://proinsias.github.io/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:francis.odonovan@gmail.com"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/francis_odonovan/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/proinsias/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url:  # "https://instagram.com/"
    - label: "KeyBase"
      icon: "fab fa-fw fa-key"
      url: "https://keybase.io/proinsias/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/francistodonovan"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1257318/proinsias"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/francisodonovan"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed  # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Analytics
analytics:
  provider: "google"  # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-79669521-1
    anonymize_ip:  # true, false (default)

# SEO Related
google_site_verification: "wtuOVsGiCFaCgBQRQKNSBUcMfBCPlGZtGV_YQtO56vo"
bing_site_verification: "23C03CE052C115F08A5835393718F084"
alexa_site_verification:
yandex_site_verification:

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environmen
