---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: An independent mind...
title_separator: '-'
subtitle: # site tagline that appears below site title in masthead
name: Francis T. O'Donovan
description: >-
  My home on the web.
url: https://proinsias.github.io
gh_repo: proinsias.github.io
github: [metadata] # https://github.com/github/pages-gem/issues/399
repository: proinsias/proinsias.github.io
email: proinsias_github_io.48ui2@aleeas.com
twitter_username: francisodonovan
github_username: proinsias
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: default
# filename of teaser fallback teaser image placed in /images/,
# e.g., "500x300.png"
teaser:
logo: # "/assets/images/88x88.png"
# breadcrumbs: false # true, false (default)
words_per_minute: 200
comments:
  # false (default), "disqus", "discourse", "facebook", "staticman",
  # "staticman_v2", "utterances", "custom"
  # yamllint disable-line rule:line-length
  provider: facebook
  disqus:
    # yamllint disable-line rule:line-length
    # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
    shortname:
  discourse:
    # yamllint disable-line rule:line-length
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook: # FIXME
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
    issue_term: # "pathname" (default)
staticman:
  allowedFields: # ['name', 'email', 'url', 'message']
  branch: # "master"
  commitMessage: # "New comment by {fields.name}"
  filename: # comment-{@timestamp}
  format: # "yml"
  moderation: # true
  path: # "/_data/comments/{options.slug}" (default)
  requiredFields: # ['name', 'email', 'message']
  transforms:
    email: # "md5"
  generatedFields:
    date:
      type: # "date"
      options:
        # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
        format:
  # URL of your own deployment with trailing slash,
  # will fallback to the public instance
  endpoint:
reCaptcha:
  siteKey:
  secret:
atom_feed: # To link to an externally hosted feed
  path: # blank (default) uses feed.xml
search: true # true, false (default)
# true, false (default). Setting to true could impact page load performance.
search_full_content:
search_provider: # lunr (default), algolia, google
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true

# Build settings
excerpt_separator: "\n\n"
incremental: false
highlighter: rouge
lsi: false
markdown: kramdown
paginate: 5 # amount of posts to show
paginate_path: /page:num/
permalink: /:categories/:title
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
remote_theme: mmistakes/minimal-mistakes
# Fail build if there is a YAML syntax error in a page's front matter.
strict_front_matter: true

# Markdown Processing
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks.
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting.
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css.
    css_class: 'highlight'

# Reading Files
include:
  - .htaccess
  - .well-known
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - /bin
  - Capfile
  - CHANGELOG
  - config
  - /docs # Ignore Minimal Mistakes /docs.
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - /templates
  - /test # Ignore Minimal Mistakes /test.
  - tmp
  - vendor
  - '*.sublime-project'
  - '*.sublime-workspace'

keep_files:
  - .git
  - .svn

# Plugins (previously gems:)
plugins:
  - jekyll-algolia
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem.
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag # Create metadata tags for search engines and social networks.
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem.
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-algolia
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

author:
  name: Francis T. O'Donovan
  avatar: /assets/images/bio-photo.jpg
  # yamllint disable-line rule:line-length
  bio: Senior Data Science Manager at Hospital IQ – Planet discoverer, researcher, developer, geek.
  location: Boston, MA
  links:
    - label: Website
      icon: fas fa-fw fa-link
      url: https://proinsias.github.io/
    - label: Email
      icon: fas fa-fw fa-envelope-square
      url: https://mailhide.io/e/fTv414zF/
    - label: Bitbucket
      icon: fab fa-fw fa-bitbucket
      url: https://bitbucket.org/francis_odonovan/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/proinsias/
    - label: Google Scholar
      icon: fab fa-fw fa-graduation-cap
      url: https://scholar.google.com/citations?user=iWEMh04AAAAJ&hl=en
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: # "https://instagram.com/"
    - label: KeyBase
      icon: fab fa-fw fa-keybase
      url: https://keybase.io/proinsias/
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/francistodonovan/
    - label: Medium
      icon: fab fa-fw fa-medium
      url: https://medium.com/@proinsias
    - label: ORCiD
      icon: fab fa-fw fa-orchid
      url: https://orcid.org/0000-0002-4858-6106
    - label: ResearchGate
      icon: fab fa-fw fa-researchgate
      url: https://www.researchgate.net/profile/Francis-Odonovan-2
    - label: StackOverflow
      icon: fab fa-fw fa-stack-overflow
      url: https://stackoverflow.com/users/1257318/proinsias/
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/francisodonovan/

# Site Footer
footer:
  links:
    - label: Website
      icon: fas fa-fw fa-link
      url: # "https://proinsias.github.io/"

defaults:
  # _posts
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: _pages
      type: 'pages'
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass/SCSS
sass:
  sass_dir: _sass
  # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

encoding: UTF-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
# Analytics
analytics:
  provider: google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-79669521-1
    anonymize_ip: # true, false (default)

# SEO Related
google_site_verification: wtuOVsGiCFaCgBQRQKNSBUcMfBCPlGZtGV_YQtO56vo
bing_site_verification: 23C03CE052C115F08A5835393718F084
alexa_site_verification:
yandex_site_verification:

compress_html:
  clippings: all
  ignore:
    envs: development # disable compression in dev environment

prose:
  rooturl: '_posts'
  siteurl: 'https://proinsias.github.io'
  media: 'assets/images'
  ignore:
    - .cspell.json
    - .editorconfig
    - /.github
    - .gitignore
    - .gitleaksignore
    - .gitlint
    - .gitpod.Dockerfile
    - .gitpod.yml
    - .jscpd.json
    - .markdown-lint-check.json
    - .markdownlint.json
    - .mdl.rb
    - .mdlrc
    - .mega-linter.yml
    - .pre-commit-config.yaml
    - .prettierignore
    - .prettierrc.json
    - .shellcheckrc
    - .sourcery.yaml
    - .textlintrc.json
    - .v8rrc.yaml
    - .yamllint.yml
    - /.well-known
    - /bin
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - project-words.txt
    - _config.yml
    - /_data
    - /_includes
    - /_layouts
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'single'
      - name: 'title'
        field:
          element: 'text'
          label: 'Post title'
          placeholder: 'Title'
          alterable: true
      - name: 'date'
        field:
          element: 'hidden'
          value: CURRENT_DATETIME
      - name: 'modified'
        field:
          element: 'hidden'
          value: CURRENT_DATETIME
      - name: 'categories'
        field:
          element: 'select'
          label: 'Select Category'
          placeholder: 'Choose Category'
          options:
            - name: 'Posts'
              value: 'posts'
            - name: 'TIL'
              value: 'til'
            - name: 'Tips'
              value: 'tips'
            - name: 'TrES'
              value: 'tres'
      # header:
      #    image: /assets/images/image_name
      #    image_description: 'danah boyd accepts her EFF award'
      #    caption: 'Courtesy of danah boyd'
      #    teaser: /assets/images/danah_boyd_eff_thumbnail.gif
      #      - name: "image"
      #        field:
      #          element: "text"
      #          label: "Add Image to Post"
      #          placeholder: "Image path (relative to /assets/post-images/)"
      #          alterable: true
      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Add Tags'
          placeholder: 'Choose Tags'
          alterable: true # A user can add additional values.
          options:
            - name: 'git'
              value: 'git'
            - name: 'Pandas'
              value: 'pandas'
            - name: 'Python'
              value: 'python'
            - name: 'SQL'
              value: 'sql'
            - name: 'TIL'
              value: 'til'
            - name: 'Tips'
              value: 'tips'
            - name: '*nix'
              value: 'nix'
