---

additional-dependency-files:
  - type: bundler-gemfile
    path: Gemfile

ignore-failures:

  ruby:
    - jekyll-gist
    - jekyll-github-metadata
    - jekyll-paginate
    - jekyll-sitemap
    - jemoji
    - ruby-lint
    - wdm
