---

name: Change Quality

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:

  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: 'Bundler Audit'
        uses: andrewmcodes/bundler-audit-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          exclude: "./.git/*"  # Optional.
          fail_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          pattern: "*.sh"  # Optional.
          reporter: github-pr-review  # Change reporter.
          shellcheck_flags: '--external-sources --format=gcc --shell=bash'

      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: '.yamllint.yml'
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label:
    name: Issue/PR Labeler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  jekyll:
    name: Jekyll Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      # TODO: Cache $BUILD_DIR/tmp/.htmlproofer - for some value of build dir.

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Speeds up installation of html-proofer.
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          # The directory to scan.
          directory: "./_site"
          # The arguments to pass to HTMLProofer.
          # Unsure how to enable alt tags for teaser images.
          # Treat urls with this domain as internal urls.
          arguments: "--check-favicon --check-html \
--empty-alt-ignore --internal-domains proinsias.github.io --only-4xx \
--url-ignore \"#,/web.archive.org/,/twitter.com/,/doi.org/\" \
--typhoeus-config '{ \"connecttimeout\": 30, \"timeout\": 30 }'"
