---

name: Cron Jobs

# yamllint disable-line rule:truthy
on:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  # Run workflow manually (without waiting for the cron to be called),
  # through the Github Actions Workflow page directly.
  workflow_dispatch:

jobs:
  cronjobs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shfmt
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install shfmt

      - name: Install hadolint
        run: |
          sudo wget --output-file /bin/hadolint \
              https://github.com/hadolint/hadolint/releases/download/v2.3.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Auto-update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.

      - name: Mark Stale Issues
        uses: actions/stale@v3.0.18
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # yamllint disable-line rule:line-length
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
          # yamllint disable-line rule:line-length
          stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
          days-before-stale: 30
          days-before-close: 5
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          exempt-issue-label: 'awaiting-approval'
          exempt-pr-label: 'awaiting-approval'

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: 'no'
          max-depth: 1

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Speeds up installation of html-proofer.
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        timeout-minutes: 30
        with:
          # The directory to scan.
          directory: "./_site"
          # The arguments to pass to HTMLProofer.
          # Unsure how to enable alt tags for teaser images.
          # Treat urls with this domain as internal urls.
          arguments: "--check-favicon --check-html \
--empty-alt-ignore --internal-domains proinsias.github.io --only-4xx \
--url-ignore \"#,/archive.org/,/twitter.com/,/doi.org/,/enkipro.com/\" \
--typhoeus-config '{ \"connecttimeout\": 30, \"timeout\": 30 }'"
